/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_developments_status = pgEnum('enum_developments_status', [
  'draft',
  'published',
  'hidden',
])
export const enum_units_unit_type = pgEnum('enum_units_unit_type', [
  'suite',
  'loft',
  'apartment',
  'penthouse',
  'house',
  'lot',
  'office',
  'other',
])
export const enum_units_record_type = pgEnum('enum_units_record_type', ['typology', 'specificUnit'])
export const enum_units_status = pgEnum('enum_units_status', [
  'available',
  'reserved',
  'sold',
  'soldOut',
  'hidden',
])
export const enum_units_pricing_currency = pgEnum('enum_units_pricing_currency', ['MXN', 'USD'])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const amenities = pgTable(
  'amenities',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    icon: varchar('icon'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('amenities_slug_idx').on(columns.slug),
    index('amenities_image_idx').on(columns.image),
    index('amenities_updated_at_idx').on(columns.updatedAt),
    index('amenities_created_at_idx').on(columns.createdAt),
  ],
)

export const cities = pgTable(
  'cities',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    state: varchar('state').notNull(),
    country: varchar('country').notNull().default('México'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('cities_slug_idx').on(columns.slug),
    index('cities_updated_at_idx').on(columns.updatedAt),
    index('cities_created_at_idx').on(columns.createdAt),
  ],
)

export const neighborhoods = pgTable(
  'neighborhoods',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    city: integer('city_id')
      .notNull()
      .references(() => cities.id, {
        onDelete: 'set null',
      }),
    description: varchar('description'),
    investmentPitch: varchar('investment_pitch'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('neighborhoods_slug_idx').on(columns.slug),
    index('neighborhoods_city_idx').on(columns.city),
    index('neighborhoods_image_idx').on(columns.image),
    index('neighborhoods_updated_at_idx').on(columns.updatedAt),
    index('neighborhoods_created_at_idx').on(columns.createdAt),
  ],
)

export const developers = pgTable(
  'developers',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    description: varchar('description'),
    website: varchar('website'),
    contactEmail: varchar('contact_email'),
    contactPhone: varchar('contact_phone'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('developers_slug_idx').on(columns.slug),
    index('developers_logo_idx').on(columns.logo),
    index('developers_updated_at_idx').on(columns.updatedAt),
    index('developers_created_at_idx').on(columns.createdAt),
  ],
)

export const developments_gallery = pgTable(
  'developments_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    caption: varchar('caption'),
  },
  (columns) => [
    index('developments_gallery_order_idx').on(columns._order),
    index('developments_gallery_parent_id_idx').on(columns._parentID),
    index('developments_gallery_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [developments.id],
      name: 'developments_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const developments_amenities = pgTable(
  'developments_amenities',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    amenity: integer('amenity_id')
      .notNull()
      .references(() => amenities.id, {
        onDelete: 'set null',
      }),
    imageOverride: integer('image_override_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    descriptionOverride: varchar('description_override'),
  },
  (columns) => [
    index('developments_amenities_order_idx').on(columns._order),
    index('developments_amenities_parent_id_idx').on(columns._parentID),
    index('developments_amenities_amenity_idx').on(columns.amenity),
    index('developments_amenities_image_override_idx').on(columns.imageOverride),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [developments.id],
      name: 'developments_amenities_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const developments_financial_model_payment_plans = pgTable(
  'developments_financial_model_payment_plans',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    discountPercent: numeric('discount_percent', { mode: 'number' }),
    downPaymentPercent: numeric('down_payment_percent', { mode: 'number' }),
    financedPercent: numeric('financed_percent', { mode: 'number' }),
    settlementPercent: numeric('settlement_percent', { mode: 'number' }),
    notes: varchar('notes'),
  },
  (columns) => [
    index('developments_financial_model_payment_plans_order_idx').on(columns._order),
    index('developments_financial_model_payment_plans_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [developments.id],
      name: 'developments_financial_model_payment_plans_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const developments = pgTable(
  'developments',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    status: enum_developments_status('status').notNull().default('draft'),
    tagline: varchar('tagline'),
    shortDescription: varchar('short_description'),
    intro: jsonb('intro'),
    developer: integer('developer_id').references(() => developers.id, {
      onDelete: 'set null',
    }),
    city: integer('city_id')
      .notNull()
      .references(() => cities.id, {
        onDelete: 'set null',
      }),
    neighborhood: integer('neighborhood_id').references(() => neighborhoods.id, {
      onDelete: 'set null',
    }),
    location_address: varchar('location_address'),
    location_postalCode: varchar('location_postal_code'),
    location_mapUrl: varchar('location_map_url'),
    location_latitude: numeric('location_latitude', { mode: 'number' }),
    location_longitude: numeric('location_longitude', { mode: 'number' }),
    location_mapImage: integer('location_map_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    heroImage: integer('hero_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    brochure: integer('brochure_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    videoUrl: varchar('video_url'),
    financialModel_pricePerSqm: numeric('financial_model_price_per_sqm', { mode: 'number' }),
    financialModel_marketPricePerSqm: numeric('financial_model_market_price_per_sqm', {
      mode: 'number',
    }),
    financialModel_spreadPercent: numeric('financial_model_spread_percent', { mode: 'number' }),
    financialModel_projectedRoiPercent: numeric('financial_model_projected_roi_percent', {
      mode: 'number',
    }),
    financialModel_roiTerm: varchar('financial_model_roi_term'),
    financialModel_projectedAppreciationPercent: numeric(
      'financial_model_projected_appreciation_percent',
      { mode: 'number' },
    ),
    financialModel_projectedAppreciationRange: varchar(
      'financial_model_projected_appreciation_range',
    ),
    financialModel_capRatePercent: numeric('financial_model_cap_rate_percent', { mode: 'number' }),
    financialModel_capRateRange: varchar('financial_model_cap_rate_range'),
    financialModel_investedCapital: numeric('financial_model_invested_capital', { mode: 'number' }),
    financialModel_deliveryEquity: numeric('financial_model_delivery_equity', { mode: 'number' }),
    financialModel_deliveryEquityRange: varchar('financial_model_delivery_equity_range'),
    financialModel_notes: varchar('financial_model_notes'),
    contact_phone: varchar('contact_phone'),
    contact_email: varchar('contact_email'),
    contact_whatsapp: varchar('contact_whatsapp'),
    contact_ctaLabel: varchar('contact_cta_label').default('Solicitar información'),
    legalDisclaimer: varchar('legal_disclaimer'),
    seo_title: varchar('seo_title'),
    seo_description: varchar('seo_description'),
    seo_image: integer('seo_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('developments_slug_idx').on(columns.slug),
    index('developments_developer_idx').on(columns.developer),
    index('developments_city_idx').on(columns.city),
    index('developments_neighborhood_idx').on(columns.neighborhood),
    index('developments_location_location_map_image_idx').on(columns.location_mapImage),
    index('developments_hero_image_idx').on(columns.heroImage),
    index('developments_brochure_idx').on(columns.brochure),
    index('developments_seo_seo_image_idx').on(columns.seo_image),
    index('developments_updated_at_idx').on(columns.updatedAt),
    index('developments_created_at_idx').on(columns.createdAt),
  ],
)

export const units_gallery = pgTable(
  'units_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    caption: varchar('caption'),
  },
  (columns) => [
    index('units_gallery_order_idx').on(columns._order),
    index('units_gallery_parent_id_idx').on(columns._parentID),
    index('units_gallery_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [units.id],
      name: 'units_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const units = pgTable(
  'units',
  {
    id: serial('id').primaryKey(),
    development: integer('development_id')
      .notNull()
      .references(() => developments.id, {
        onDelete: 'set null',
      }),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    unitType: enum_units_unit_type('unit_type'),
    recordType: enum_units_record_type('record_type').notNull().default('typology'),
    status: enum_units_status('status').notNull().default('available'),
    pricing_price: numeric('pricing_price', { mode: 'number' }),
    pricing_currency: enum_units_pricing_currency('pricing_currency').default('MXN'),
    pricing_isStartingPrice: boolean('pricing_is_starting_price').default(true),
    pricing_priceLabel: varchar('pricing_price_label'),
    attributes_interiorArea: numeric('attributes_interior_area', { mode: 'number' }),
    attributes_terraceArea: numeric('attributes_terrace_area', { mode: 'number' }),
    attributes_totalArea: numeric('attributes_total_area', { mode: 'number' }),
    attributes_bedrooms: numeric('attributes_bedrooms', { mode: 'number' }),
    attributes_bathrooms: numeric('attributes_bathrooms', { mode: 'number' }),
    attributes_halfBathrooms: numeric('attributes_half_bathrooms', { mode: 'number' }),
    attributes_parkingSpaces: numeric('attributes_parking_spaces', { mode: 'number' }),
    attributes_hasTerrace: boolean('attributes_has_terrace'),
    attributes_floor: varchar('attributes_floor'),
    floorPlan: integer('floor_plan_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    description: varchar('description'),
    featured: boolean('featured').default(false),
    sortOrder: numeric('sort_order', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('units_development_idx').on(columns.development),
    index('units_floor_plan_idx').on(columns.floorPlan),
    index('units_updated_at_idx').on(columns.updatedAt),
    index('units_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    amenitiesID: integer('amenities_id'),
    citiesID: integer('cities_id'),
    neighborhoodsID: integer('neighborhoods_id'),
    developersID: integer('developers_id'),
    developmentsID: integer('developments_id'),
    unitsID: integer('units_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_amenities_id_idx').on(columns.amenitiesID),
    index('payload_locked_documents_rels_cities_id_idx').on(columns.citiesID),
    index('payload_locked_documents_rels_neighborhoods_id_idx').on(columns.neighborhoodsID),
    index('payload_locked_documents_rels_developers_id_idx').on(columns.developersID),
    index('payload_locked_documents_rels_developments_id_idx').on(columns.developmentsID),
    index('payload_locked_documents_rels_units_id_idx').on(columns.unitsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['amenitiesID']],
      foreignColumns: [amenities.id],
      name: 'payload_locked_documents_rels_amenities_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['citiesID']],
      foreignColumns: [cities.id],
      name: 'payload_locked_documents_rels_cities_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['neighborhoodsID']],
      foreignColumns: [neighborhoods.id],
      name: 'payload_locked_documents_rels_neighborhoods_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['developersID']],
      foreignColumns: [developers.id],
      name: 'payload_locked_documents_rels_developers_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['developmentsID']],
      foreignColumns: [developments.id],
      name: 'payload_locked_documents_rels_developments_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['unitsID']],
      foreignColumns: [units.id],
      name: 'payload_locked_documents_rels_units_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_amenities = relations(amenities, ({ one }) => ({
  image: one(media, {
    fields: [amenities.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_cities = relations(cities, () => ({}))
export const relations_neighborhoods = relations(neighborhoods, ({ one }) => ({
  city: one(cities, {
    fields: [neighborhoods.city],
    references: [cities.id],
    relationName: 'city',
  }),
  image: one(media, {
    fields: [neighborhoods.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_developers = relations(developers, ({ one }) => ({
  logo: one(media, {
    fields: [developers.logo],
    references: [media.id],
    relationName: 'logo',
  }),
}))
export const relations_developments_gallery = relations(developments_gallery, ({ one }) => ({
  _parentID: one(developments, {
    fields: [developments_gallery._parentID],
    references: [developments.id],
    relationName: 'gallery',
  }),
  image: one(media, {
    fields: [developments_gallery.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_developments_amenities = relations(developments_amenities, ({ one }) => ({
  _parentID: one(developments, {
    fields: [developments_amenities._parentID],
    references: [developments.id],
    relationName: 'amenities',
  }),
  amenity: one(amenities, {
    fields: [developments_amenities.amenity],
    references: [amenities.id],
    relationName: 'amenity',
  }),
  imageOverride: one(media, {
    fields: [developments_amenities.imageOverride],
    references: [media.id],
    relationName: 'imageOverride',
  }),
}))
export const relations_developments_financial_model_payment_plans = relations(
  developments_financial_model_payment_plans,
  ({ one }) => ({
    _parentID: one(developments, {
      fields: [developments_financial_model_payment_plans._parentID],
      references: [developments.id],
      relationName: 'financialModel_paymentPlans',
    }),
  }),
)
export const relations_developments = relations(developments, ({ one, many }) => ({
  developer: one(developers, {
    fields: [developments.developer],
    references: [developers.id],
    relationName: 'developer',
  }),
  city: one(cities, {
    fields: [developments.city],
    references: [cities.id],
    relationName: 'city',
  }),
  neighborhood: one(neighborhoods, {
    fields: [developments.neighborhood],
    references: [neighborhoods.id],
    relationName: 'neighborhood',
  }),
  location_mapImage: one(media, {
    fields: [developments.location_mapImage],
    references: [media.id],
    relationName: 'location_mapImage',
  }),
  heroImage: one(media, {
    fields: [developments.heroImage],
    references: [media.id],
    relationName: 'heroImage',
  }),
  gallery: many(developments_gallery, {
    relationName: 'gallery',
  }),
  brochure: one(media, {
    fields: [developments.brochure],
    references: [media.id],
    relationName: 'brochure',
  }),
  amenities: many(developments_amenities, {
    relationName: 'amenities',
  }),
  financialModel_paymentPlans: many(developments_financial_model_payment_plans, {
    relationName: 'financialModel_paymentPlans',
  }),
  seo_image: one(media, {
    fields: [developments.seo_image],
    references: [media.id],
    relationName: 'seo_image',
  }),
}))
export const relations_units_gallery = relations(units_gallery, ({ one }) => ({
  _parentID: one(units, {
    fields: [units_gallery._parentID],
    references: [units.id],
    relationName: 'gallery',
  }),
  image: one(media, {
    fields: [units_gallery.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_units = relations(units, ({ one, many }) => ({
  development: one(developments, {
    fields: [units.development],
    references: [developments.id],
    relationName: 'development',
  }),
  floorPlan: one(media, {
    fields: [units.floorPlan],
    references: [media.id],
    relationName: 'floorPlan',
  }),
  gallery: many(units_gallery, {
    relationName: 'gallery',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    amenitiesID: one(amenities, {
      fields: [payload_locked_documents_rels.amenitiesID],
      references: [amenities.id],
      relationName: 'amenities',
    }),
    citiesID: one(cities, {
      fields: [payload_locked_documents_rels.citiesID],
      references: [cities.id],
      relationName: 'cities',
    }),
    neighborhoodsID: one(neighborhoods, {
      fields: [payload_locked_documents_rels.neighborhoodsID],
      references: [neighborhoods.id],
      relationName: 'neighborhoods',
    }),
    developersID: one(developers, {
      fields: [payload_locked_documents_rels.developersID],
      references: [developers.id],
      relationName: 'developers',
    }),
    developmentsID: one(developments, {
      fields: [payload_locked_documents_rels.developmentsID],
      references: [developments.id],
      relationName: 'developments',
    }),
    unitsID: one(units, {
      fields: [payload_locked_documents_rels.unitsID],
      references: [units.id],
      relationName: 'units',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_developments_status: typeof enum_developments_status
  enum_units_unit_type: typeof enum_units_unit_type
  enum_units_record_type: typeof enum_units_record_type
  enum_units_status: typeof enum_units_status
  enum_units_pricing_currency: typeof enum_units_pricing_currency
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  amenities: typeof amenities
  cities: typeof cities
  neighborhoods: typeof neighborhoods
  developers: typeof developers
  developments_gallery: typeof developments_gallery
  developments_amenities: typeof developments_amenities
  developments_financial_model_payment_plans: typeof developments_financial_model_payment_plans
  developments: typeof developments
  units_gallery: typeof units_gallery
  units: typeof units
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_amenities: typeof relations_amenities
  relations_cities: typeof relations_cities
  relations_neighborhoods: typeof relations_neighborhoods
  relations_developers: typeof relations_developers
  relations_developments_gallery: typeof relations_developments_gallery
  relations_developments_amenities: typeof relations_developments_amenities
  relations_developments_financial_model_payment_plans: typeof relations_developments_financial_model_payment_plans
  relations_developments: typeof relations_developments
  relations_units_gallery: typeof relations_units_gallery
  relations_units: typeof relations_units
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
