/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    amenities: Amenity;
    cities: City;
    neighborhoods: Neighborhood;
    developers: Developer;
    developments: Development;
    units: Unit;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    developments: {
      units: 'units';
    };
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    neighborhoods: NeighborhoodsSelect<false> | NeighborhoodsSelect<true>;
    developers: DevelopersSelect<false> | DevelopersSelect<true>;
    developments: DevelopmentsSelect<false> | DevelopmentsSelect<true>;
    units: UnitsSelect<false> | UnitsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: number;
  name: string;
  /**
   * Se genera automáticamente desde "name" si lo dejas vacío.
   */
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Nombre interno del icono, si se usa en el frontend.
   */
  icon?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  /**
   * Se genera automáticamente desde "name" si lo dejas vacío.
   */
  slug: string;
  state: string;
  country: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "neighborhoods".
 */
export interface Neighborhood {
  id: number;
  name: string;
  /**
   * Se genera automáticamente desde "name" si lo dejas vacío.
   */
  slug: string;
  city: number | City;
  description?: string | null;
  /**
   * Texto comercial breve sobre plusvalía, estilo de vida o atractivo de la zona.
   */
  investmentPitch?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developers".
 */
export interface Developer {
  id: number;
  name: string;
  /**
   * Se genera automáticamente desde "name" si lo dejas vacío.
   */
  slug: string;
  logo?: (number | null) | Media;
  description?: string | null;
  website?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developments".
 */
export interface Development {
  id: number;
  name: string;
  /**
   * Se genera automáticamente desde "name" si lo dejas vacío.
   */
  slug: string;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published' | 'hidden';
  description?: string | null;
  /**
   * Ej. Providencia | Guadalajara
   */
  tagline?: string | null;
  /**
   * Muestra este desarrollo en la sección "Proyectos" de la home.
   */
  featuredOnHome?: boolean | null;
  /**
   * Orden dentro de la sección (menor número = primero).
   */
  homeSortOrder?: number | null;
  /**
   * Etiqueta opcional sobre la imagen. Ej. "Últimas unidades".
   */
  homeBadge?: string | null;
  /**
   * Ej. "$2.2 mdp". Si se deja vacío se muestra "Precio por definir".
   */
  homeStartingPriceLabel?: string | null;
  /**
   * Descripción corta para la tarjeta. Si se deja vacío se usa "tagline".
   */
  homeShortDescription?: string | null;
  location?: {
    address?: string | null;
    neighborhood?: string | null;
    postalCode?: string | null;
    city?: string | null;
    state?: string | null;
    /**
     * Imagen del mapa de ubicación.
     */
    map?: (number | null) | Media;
  };
  amenities?:
    | {
        amenity: number | Amenity;
        /**
         * Imagen específica de este desarrollo para la amenidad. Si se deja vacío se usa la imagen default de la amenidad.
         */
        imageOverride?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  units?: {
    docs?: (number | Unit)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  investmentSnapshot?: {
    pricePerSqm?: number | null;
    marketPricePerSqm?: number | null;
    spread?: number | null;
    projectedRoi?: number | null;
    deliveryMonths?: number | null;
    investedCapitalAtDelivery?: number | null;
    projectedAppreciationLow?: number | null;
    projectedAppreciationHigh?: number | null;
    /**
     * Calculado: (baja + alta) / 2.
     */
    projectedAppreciationMid?: number | null;
    capRateLow?: number | null;
    capRateHigh?: number | null;
    /**
     * Calculado: (bajo + alto) / 2.
     */
    capRateMid?: number | null;
    equityAtDeliveryLow?: number | null;
    equityAtDeliveryHigh?: number | null;
    /**
     * Calculado: (bajo + alto) / 2.
     */
    equityAtDeliveryMid?: number | null;
  };
  paymentPlans?:
    | {
        name: string;
        discountPercent?: number | null;
        chart?: (number | null) | Media;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units".
 */
export interface Unit {
  id: number;
  development: number | Development;
  name: string;
  /**
   * Se genera automáticamente desde "name" si lo dejas vacío.
   */
  slug: string;
  unitType?: ('suite' | 'loft' | 'apartment' | 'penthouse' | 'house' | 'lot' | 'office' | 'other') | null;
  recordType: 'typology' | 'specificUnit';
  status: 'available' | 'reserved' | 'sold' | 'soldOut' | 'hidden';
  pricing?: {
    price?: number | null;
    currency?: ('MXN' | 'USD') | null;
    isStartingPrice?: boolean | null;
    /**
     * Ej. Desde $4.5 MDP o SOLD OUT.
     */
    priceLabel?: string | null;
  };
  attributes?: {
    interiorArea?: number | null;
    terraceArea?: number | null;
    totalArea?: number | null;
    bedrooms?: number | null;
    bathrooms?: number | null;
    halfBathrooms?: number | null;
    parkingSpaces?: number | null;
    hasTerrace?: boolean | null;
    floor?: string | null;
  };
  floorPlan?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'amenities';
        value: number | Amenity;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'neighborhoods';
        value: number | Neighborhood;
      } | null)
    | ({
        relationTo: 'developers';
        value: number | Developer;
      } | null)
    | ({
        relationTo: 'developments';
        value: number | Development;
      } | null)
    | ({
        relationTo: 'units';
        value: number | Unit;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  state?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "neighborhoods_select".
 */
export interface NeighborhoodsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  city?: T;
  description?: T;
  investmentPitch?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developers_select".
 */
export interface DevelopersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  description?: T;
  website?: T;
  contactEmail?: T;
  contactPhone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developments_select".
 */
export interface DevelopmentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  status?: T;
  description?: T;
  tagline?: T;
  featuredOnHome?: T;
  homeSortOrder?: T;
  homeBadge?: T;
  homeStartingPriceLabel?: T;
  homeShortDescription?: T;
  location?:
    | T
    | {
        address?: T;
        neighborhood?: T;
        postalCode?: T;
        city?: T;
        state?: T;
        map?: T;
      };
  amenities?:
    | T
    | {
        amenity?: T;
        imageOverride?: T;
        id?: T;
      };
  units?: T;
  investmentSnapshot?:
    | T
    | {
        pricePerSqm?: T;
        marketPricePerSqm?: T;
        spread?: T;
        projectedRoi?: T;
        deliveryMonths?: T;
        investedCapitalAtDelivery?: T;
        projectedAppreciationLow?: T;
        projectedAppreciationHigh?: T;
        projectedAppreciationMid?: T;
        capRateLow?: T;
        capRateHigh?: T;
        capRateMid?: T;
        equityAtDeliveryLow?: T;
        equityAtDeliveryHigh?: T;
        equityAtDeliveryMid?: T;
      };
  paymentPlans?:
    | T
    | {
        name?: T;
        discountPercent?: T;
        chart?: T;
        notes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units_select".
 */
export interface UnitsSelect<T extends boolean = true> {
  development?: T;
  name?: T;
  slug?: T;
  unitType?: T;
  recordType?: T;
  status?: T;
  pricing?:
    | T
    | {
        price?: T;
        currency?: T;
        isStartingPrice?: T;
        priceLabel?: T;
      };
  attributes?:
    | T
    | {
        interiorArea?: T;
        terraceArea?: T;
        totalArea?: T;
        bedrooms?: T;
        bathrooms?: T;
        halfBathrooms?: T;
        parkingSpaces?: T;
        hasTerrace?: T;
        floor?: T;
      };
  floorPlan?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  description?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}